name: Changelog generate

on:
  push:
    branches:
      - master
      - develop
      - 'releases/*'
    tags:
      - v1.*

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run changelog gradle task
        run: |
          gradle test
          gradle changelog
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: failed-tests
          path: plugin/build/reports/tests/

      - uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: build/outputs/changelog.md

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: plugin/build/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true

  publish_pre_release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/releases/')
    needs: changelog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: changelog

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: changelog.md
          draft: false
          prerelease: true

  publish_draft:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    needs: changelog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: changelog

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: changelog.md
          draft: true
          prerelease: true

  publish:
    if: github.event_name == 'push' && contains(github.ref, 'v1.')
    needs: changelog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/download-artifact@v2
        with:
          name: changelog

      - name: Run publish gradle task
        run: |
          gradle publishPlugins -Pgradle.publish.key=${{ secrets.KEY }} -Pgradle.publish.secret=${{ secrets.SECRET }}
          gradle publish
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USERNAME: ${{ secrets.USER_NAME }}

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: changelog.md
          draft: false
          prerelease: false
